return {
  "nvim-treesitter/nvim-treesitter",
  event = { "BufReadPre", "BufNewFile" },
  build = ":TSUpdate",
  dependencies = {
    "windwp/nvim-ts-autotag",
    "nvim-treesitter/nvim-treesitter-textobjects",
  },
  config = function()
    local treesitter = require("nvim-treesitter.configs")

    treesitter.setup({
      highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
      },
      indent = { enable = true },
      autotag = {
        enable = true,
      },
      ensure_installed = {
        "asm",
        "asm",
        "bash",
        "c",
        "c_sharp",
        "cmake",
        "cpp",
        "css",
        "csv",
        "dart",
        "desktop",
        "dockerfile",
        "dot",
        "fish",
        "fsharp",
        "gitignore",
        "gnuplot",
        "go",
        "haskell",
        "html",
        "http",
        "java",
        "javascript",
        "json",
        "llvm",
        "lua",
        "markdown",
        "markdown_inline",
        "mermaid",
        "nasm",
        "nginx",
        "objdump",
        "ocaml",
        "perl",
        "php",
        "python",
        "racket",
        "regex",
        "rust",
        "sql",
        "toml",
        "tsv",
        "tsx",
        "typescript",
        "typst",
        "verilog",
        "vim",
        "xml",
        "yaml",
        "zig",
      },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = "<C-space>",
          node_incremental = "<C-space>",
          scope_incremental = false,
          node_decremental = "<bs>",
        },
      },
      rainbow = {
        enable = true,
        disable = { "html" },
        extended_mode = false,
        max_file_lines = nil,
      },
      context_commentstring = {
        enable = true,
        enable_autocmd = false,
      },
    })
  end,
}
